---
# tasks file for roles/haproxy
- block:
    - name: Install haproxy
      yum:
        name: haproxy
        state: present
    - name: Import Template - haproxy.cfg.j2
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: Start haproxy
      service:
        name: haproxy
        state: started
        enabled: yes
    - name: Open FW
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
  when: ansible_facts.hostname == "host1"

