- name: Install apache2 Service
  apt:
    name: apache2
    state: latest
- name: Start apache2 Service
  service:
    name: apache2
    state: started
    enabled: yes
- name: Copy index.html
  template:
    src: index.html
    dest: /var/www/html
- name: Open UFW
  ufw:
    rule: allow
    port: "80"
    proto: tcp