---
# tasks file for roles/docker
- name: Install at CentOS
  include_tasks: setup-CentOS-docker.yml
  when: ansible_distribution == "CentOS"
- name: Install at Ubuntu
  include_tasks: setup-Ubuntu-docker.yml
  when: ansible_distribution == "Ubuntu"