---
- name: register_loop_when_quiz2
  hosts: host1
  gather_facts: no
  vars:
    guro:
      - first
      - second
      - third
  tasks:
    - name: list exam
      debug:
        msg: "{{ item }}"
      loop: "{{ guro }}"
      when: item == "second"
