---
- name: Deploy apapche service
  hosts: web
  become: true
  remote_user: user
  tasks:
    - name: "{{ pkg_name }} will be installed" # " " 인자 1개
      yum:
        name: "{{ pkg_name }}" # { } 로 시작하는 value는 " " 처리
        state: latest
      register: yum_reg
    - name: start {{ svc_name }}
      service:
        name: "{{ svc_name }}"
        state: started
        enabled: yes
      register: service_reg
    - name: config index.html
      copy:
        src: index.html
        dest: /var/www/html/
        notify:
          - restart httpd
      register: copy_reg
    - name: Open {{ fw_name }}
      firewalld:
        service: "{{ fw_name }}"
        permanent: yes
        state: enabled
        immediate: yes
      register: fw_reg
    - name: Open regs
      debug:
        var: yum_reg.rc
    - debug:
        var: service_reg
    - debug:
        var: copy_reg
    - debug:
        var: fw_reg
  handlers:
    - name: restart {{ svc_name }}
      service:
        name: "{{ svc_name }}"
        state: restarted

- name: Deploy Database
  hosts: db
  remote_user: user
  become: yes
  tasks:
    - name: "{{ pkg_name }} will be installed"
      yum:
        name: "{{ pkg_name }}"
        state: latest
    - name: Start {{ svc_name }}
      service:
        name: "{{ svc_name }}"
        state: started
        enabled: yes
    - name: Open {{ fw_name }}
      firewalld:
        service: "{{ fw_name }}"
        permanent: yes
        state: enabled
        immediate: yes