---
- name: register practice
  hosts: host1
  become: yes
  tasks:
    - name: Download file and force basic auth
      get_url:
        url: http://192.168.10.100/reg_prac.sh
        dest: /tmp/reg_prac.sh
        mode: '755'
    - name: Start shell
      shell: /tmp/reg_prac.sh register
      register: reg1
    - name: Print Stdout
      debug:
        var: reg1.stdout
      when: reg1.rc == 0